services:
  - type: web
    name: communityhub-api-persadenis
    runtime: docker
    repo: https://github.com/persadenis/UBB-SE-2026-CommunityHub
    branch: main
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
      - key: DatabaseProvider
        value: PostgreSQL
      - key: ConnectionStrings__ChatAndEventsDB
        fromDatabase:
          name: communityhub-db
          property: connectionString

  - type: web
    name: communityhub-web-persadenis
    runtime: docker
    repo: https://github.com/persadenis/UBB-SE-2026-CommunityHub
    branch: main
    dockerfilePath: ./Dockerfile.web
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
      - key: DatabaseProvider
        value: PostgreSQL
      - key: Api__BaseAddress
        value: https://communityhub-api-persadenis.onrender.com/
      - key: ConnectionStrings__ChatAndEventsDB
        fromDatabase:
          name: communityhub-db
          property: connectionString

databases:
  - name: communityhub-db
    databaseName: communityhub
    user: communityhub
    plan: free
