// <auto-generated />
using System;
using ChatAndEvents.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatAndEvents.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506175515_SeedAchievements")]
    partial class SeedAchievements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMessagePreview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PinnedMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PinnedMessageId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Friend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMatch")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId2");

                    b.HasIndex("UserId1", "UserId2")
                        .IsUnique();

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttachmentImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Content")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<string>("LinkPreviewDesc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkPreviewTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PinExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReplyToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentMessageId");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastReadMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nickname")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("LastReadMessageId");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Achievement", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AchievementId");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            AchievementId = 1,
                            Description = "Attend your first event.",
                            IsUnlocked = false,
                            Name = "First Steps"
                        },
                        new
                        {
                            AchievementId = 2,
                            Description = "Create 3 events.",
                            IsUnlocked = false,
                            Name = "Proper Host"
                        },
                        new
                        {
                            AchievementId = 3,
                            Description = "Approve 25 quest submissions.",
                            IsUnlocked = false,
                            Name = "Quest Solver"
                        },
                        new
                        {
                            AchievementId = 4,
                            Description = "Add 50 memories with photos.",
                            IsUnlocked = false,
                            Name = "Memory Keeper"
                        },
                        new
                        {
                            AchievementId = 5,
                            Description = "Send 100 discussion messages.",
                            IsUnlocked = false,
                            Name = "Social Butterfly"
                        },
                        new
                        {
                            AchievementId = 6,
                            Description = "Attend 10 events.",
                            IsUnlocked = false,
                            Name = "Event Veteran"
                        },
                        new
                        {
                            AchievementId = 7,
                            Description = "Complete every quest in an event.",
                            IsUnlocked = false,
                            Name = "Perfectionist"
                        });
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.AnnouncementReaction", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("AnnouncementId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("AnnouncementReactions");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.AnnouncementReadReceipt", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AnnouncementId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AnnouncementReadReceipts");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.AttendedEvent", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<int>("UnreadAnnouncementCount")
                        .HasColumnType("int");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("AttendedEvents");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Title = "NATURE"
                        },
                        new
                        {
                            CategoryId = 2,
                            Title = "FITNESS"
                        },
                        new
                        {
                            CategoryId = 3,
                            Title = "MUSIC"
                        },
                        new
                        {
                            CategoryId = 4,
                            Title = "SOCIAL"
                        },
                        new
                        {
                            CategoryId = 5,
                            Title = "ART"
                        },
                        new
                        {
                            CategoryId = 6,
                            Title = "PETS"
                        },
                        new
                        {
                            CategoryId = 7,
                            Title = "TECH"
                        },
                        new
                        {
                            CategoryId = 8,
                            Title = "FUN"
                        });
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.DiscussionMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssociatedEventEventId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<string>("MediaPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReplyToId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedEventEventId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ReplyToId");

                    b.ToTable("DiscussionMessages");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.DiscussionMute", b =>
                {
                    b.Property<int>("DiscussionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("bit");

                    b.Property<Guid>("MutedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("MutedUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MutedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DiscussionId", "UserId");

                    b.HasIndex("MutedById");

                    b.HasIndex("MutedUserId");

                    b.ToTable("DiscussionMutes");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.DiscussionReaction", b =>
                {
                    b.Property<int>("DiscussionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.HasKey("DiscussionId", "UserId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MessageId");

                    b.ToTable("DiscussionReactions");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("int");

                    b.Property<string>("EventBannerPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaximumPeople")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SlowModeSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("AdminId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Memory", b =>
                {
                    b.Property<int>("MemoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemoryId"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemoryId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("EventId");

                    b.ToTable("Memories", (string)null);
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.MemoryLike", b =>
                {
                    b.Property<int>("MemoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemoryId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("MemoryLikes", (string)null);
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrerequisiteQuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PrerequisiteQuestId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.QuestMemory", b =>
                {
                    b.Property<int>("QuestId")
                        .HasColumnType("int");

                    b.Property<int>("MemoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProofStatus")
                        .HasColumnType("int");

                    b.HasKey("QuestId", "MemoryId");

                    b.HasIndex("MemoryId");

                    b.ToTable("QuestMemories");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReputationPoints")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.UserReputationScore", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReputationPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Newcomer");

                    b.HasKey("UserId");

                    b.ToTable("users_RP_scores", (string)null);
                });

            modelBuilder.Entity("Events_GSS.Data.Models.Discussion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("EventId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Conversation", b =>
                {
                    b.HasOne("ChatAndEvents.Data.ChatData.domain.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.Message", "PinnedMessage")
                        .WithMany()
                        .HasForeignKey("PinnedMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("PinnedMessage");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Friend", b =>
                {
                    b.HasOne("ChatAndEvents.Data.ChatData.domain.User", "User1")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.User", "User2")
                        .WithMany()
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Message", b =>
                {
                    b.HasOne("ChatAndEvents.Data.ChatData.domain.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.Message", "ParentMessage")
                        .WithMany()
                        .HasForeignKey("ParentMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.Message", "ReplyTo")
                        .WithMany()
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conversation");

                    b.Navigation("ParentMessage");

                    b.Navigation("ReplyTo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Participant", b =>
                {
                    b.HasOne("ChatAndEvents.Data.ChatData.domain.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.Message", "LastReadMessage")
                        .WithMany()
                        .HasForeignKey("LastReadMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("LastReadMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Announcement", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Event", "Event")
                        .WithMany("Announcements")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.AnnouncementReaction", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Announcement", "Announcement")
                        .WithMany("Reactions")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.AnnouncementReadReceipt", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Announcement", "Announcement")
                        .WithMany("ReadReceipts")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.ChatData.domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.AttendedEvent", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Event", "Event")
                        .WithMany("Attendees")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.DiscussionMessage", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Event", "AssociatedEvent")
                        .WithMany()
                        .HasForeignKey("AssociatedEventEventId");

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId");

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.DiscussionMessage", "ReplyTo")
                        .WithMany()
                        .HasForeignKey("ReplyToId");

                    b.Navigation("AssociatedEvent");

                    b.Navigation("Author");

                    b.Navigation("ReplyTo");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.DiscussionMute", b =>
                {
                    b.HasOne("Events_GSS.Data.Models.Discussion", "Discussion")
                        .WithMany("Mutes")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "MutedBy")
                        .WithMany()
                        .HasForeignKey("MutedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "MutedUser")
                        .WithMany()
                        .HasForeignKey("MutedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Discussion");

                    b.Navigation("MutedBy");

                    b.Navigation("MutedUser");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.DiscussionReaction", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Events_GSS.Data.Models.Discussion", "Discussion")
                        .WithMany("Reactions")
                        .HasForeignKey("DiscussionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.DiscussionMessage", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Discussion");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Event", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Memory", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Event", "Event")
                        .WithMany("Memories")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.MemoryLike", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Memory", "Memory")
                        .WithMany("Likes")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Notification", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Quest", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Event", "Event")
                        .WithMany("Quests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Quest", "PrerequisiteQuest")
                        .WithMany()
                        .HasForeignKey("PrerequisiteQuestId");

                    b.Navigation("Event");

                    b.Navigation("PrerequisiteQuest");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.QuestMemory", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Memory", "Proof")
                        .WithMany()
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Quest", "ForQuest")
                        .WithMany("QuestMemories")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForQuest");

                    b.Navigation("Proof");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.UserReputationScore", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "User")
                        .WithOne("ReputationScore")
                        .HasForeignKey("ChatAndEvents.Data.EventsData.Models.UserReputationScore", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Events_GSS.Data.Models.Discussion", b =>
                {
                    b.HasOne("ChatAndEvents.Data.EventsData.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatAndEvents.Data.EventsData.Models.Event", "AssociatedEvent")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedEvent");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ChatAndEvents.Data.ChatData.domain.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Announcement", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("ReadReceipts");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.DiscussionMessage", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Event", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Attendees");

                    b.Navigation("Memories");

                    b.Navigation("Quests");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Memory", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.Quest", b =>
                {
                    b.Navigation("QuestMemories");
                });

            modelBuilder.Entity("ChatAndEvents.Data.EventsData.Models.User", b =>
                {
                    b.Navigation("ReputationScore");
                });

            modelBuilder.Entity("Events_GSS.Data.Models.Discussion", b =>
                {
                    b.Navigation("Mutes");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
